import groovy.transform.Field

@Field final String nodeVersion = '10.4.1'

def windowsStep () {
  node(label: 'windows') {
    ansiColor('xterm') {
      bat 'git config --global core.autocrlf input'
      checkout scm
      fileExists 'package.json'
      nodejs(nodeVersion) {
        bat 'del /s /q node_modules >nul 2>&1'
        bat 'npx yarn@1.9.4 config set msvs_version 2015 --global'
        bat 'npm install'
        bat 'npm run lint'
        bat 'npm run build'
        archiveArtifacts 'dist\\*'
        cleanWs()
      }
    }
  }
}

def unixStep(nodeLabel) {
  node(label: nodeLabel) {
    ansiColor('xterm') {
      checkout scm
      fileExists 'package.json'
      nodejs(nodeVersion) {
        sh 'rm -rf node_modules/'
        sh 'npm install'
        sh 'npm run lint'
        sh 'npm run build'
        archiveArtifacts 'dist/*'
        cleanWs()
      }
    }
  }
}

stage('Builds') {
  parallel(
    "windows": windowsStep(),
    "macos": unixStep("macos"),
    "linux": unixStep("linux")
  )
}
